### ISSUE TITLE
dwdatareader for macOS

### ISSUE THREAD

**Issue by okurtulu** [costerwi/dwdatareader#59]
Hello, i wanted to check if there is a solution to get dwdatareader to work under macOS operating environment?

**Comment by costerwi** [comment]
Unfortunately, Dewesoft presently only offers [its programming libraries](https://download.dewesoft.com/list/developers/dewesoft-data-reader-library) for Linux and Windows (and only for Intel hardware). You could ask them to add a macOS library. Otherwise:

- You could virtualize a Linux or Windows OS inside your mac. If you have Apple silicon then this might be more difficult and less efficient.
- You could run online like [my binder example](https://mybinder.org/v2/gh/costerwi/dwdatareader/master?labpath=dwdatareader_example.ipynb) or Google Colab or similar. 

Thanks
